authentication = [
  {
    mechanism = password_based
    backend = http
    url = "http://backend:8000/internal/auth/mqtt"
    method = post
    body {
      username = "${username}"
      password = "${password}"
      client_id = "${clientid}"
    }
    headers { "Content-Type" = "application/json" }
  }
]

authorization {
  no_match = deny
  deny_action = disconnect
  sources = [
    {
      type = http
      url = "http://backend:8000/internal/auth/mqtt/acl"
      method = post
      body {
        username = "${username}"
        topic = "${topic}"
        action = "${action}"
        client_id = "${clientid}"
      }
      headers { "Content-Type" = "application/json" }
    }
  ]
}

log {
  level = warning
}

listeners {
  tcp.default {
    enable = true
    bind = "0.0.0.0:1883"
    max_connections = 1024000
  }
  ws.default {
    enable = true
    bind = "0.0.0.0:8083"
    path = "/mqtt"
  }
}

dashboard {
  listeners {
    http {
      enable = true
      bind = "0.0.0.0:18083"
    }
  }
}
